### ISSUE TITLE
The password reset page is broken

### ISSUE THREAD

**Issue by dpeukert** [DevWars/devwars.tv-old#6]
![](http://i.imgur.com/ZoeND2z.png)

**Comment by b3zman41** [comment]
Seems to be a problem with the build process, gonna look into the minifier and see what's up.

**Comment by ChrisRu** [comment]
Seems still broken? When I press the 'reset password' button after filling in my email address it fires a GET request on `https://devwars.tv/v1/user/initreset`. Getting a `409` error with response: `You must be a native DevWars User`
